import { hasHouseholdKey, refuse } from "@/lib/auth";
import { clearAttendance, listDecisions, setAttendance } from "@/lib/attendance";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });

export async function GET(req: Request) {
  if (!hasHouseholdKey(req)) return refuse();
  try {
    return json({ decisions: await listDecisions() });
  } catch (err) {
    console.error("[api/attendance]", err);
    return json({ error: "Could not reach the database." }, 500);
  }
}

/**
 * Recording which of two clashing commitments she is actually at.
 *
 * Keyed on the occurrence, so declining one practice does not disturb the rule
 * that generates practice, and one week of a weekly tutoring slot can be
 * dropped without cancelling the rest.
 */
export async function POST(req: Request) {
  if (!hasHouseholdKey(req)) return refuse();

  let body: { occurrenceId?: string; attending?: boolean; note?: string; clear?: boolean };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Expected JSON" }, 400);
  }

  const id = (body.occurrenceId ?? "").trim();
  // Occurrence ids are generated by the schedule, so this only has to be sane.
  if (!id || id.length > 200) return json({ error: "Bad occurrence id" }, 400);

  try {
    if (body.clear) {
      await clearAttendance(id);
      return json({ occurrenceId: id, cleared: true });
    }
    const attending = body.attending !== false;
    await setAttendance(id, attending, body.note ?? "");
    return json({ occurrenceId: id, attending });
  } catch (err) {
    console.error("[api/attendance]", err);
    return json({ error: "Could not save that." }, 500);
  }
}
