import { hasHouseholdKey, refuse } from "@/lib/auth";
import { clearNudge, doneNudges, markNudgeDone } from "@/lib/nudges";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });

/** Which reminders and clashes have already been dealt with. */
export async function GET(req: Request) {
  if (!hasHouseholdKey(req)) return refuse();
  try {
    return json({ done: [...(await doneNudges())] });
  } catch (err) {
    console.error("[api/nudges]", err);
    return json({ error: "Could not reach the database." }, 500);
  }
}

/** Ticking a nudge off, and undoing that. */
export async function POST(req: Request) {
  if (!hasHouseholdKey(req)) return refuse();

  let body: { id?: string; done?: boolean };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Expected JSON" }, 400);
  }

  const id = (body.id ?? "").trim();
  // Ids are generated by lib/guidance.ts, so this only has to be sane.
  if (!id || id.length > 200) return json({ error: "Bad nudge id" }, 400);

  try {
    if (body.done === false) await clearNudge(id);
    else await markNudgeDone(id);
    return json({ id, done: body.done !== false });
  } catch (err) {
    console.error("[api/nudges]", err);
    return json({ error: "Could not save that." }, 500);
  }
}
